[package]
name = "rocket_server"
version = "0.1.0"
authors = ["omershlo <omer.shlomovits@gmail.com>"]
edition = "2018"



[dependencies]
rocket = "0.4.0"
rocket_contrib = "0.4.0"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

reqwest = "0.9.5"
uuid = { version = "0.7", features = ["v4"] }