[package]
name = "relay-server-common"
version = "0.1.0"
authors = ["Avi <kozokinavi@gmail.com>", "Alex Manuskin <amanusk@protonmail.com>"]
edition = "2018"

[dependencies]
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
tokio-core = "0.1"
byteorder = "1.0"
log = "0.4"
futures = "0.1"
