[package]
name = "relay-server-common"
version = "0.1.0"
authors = ["Avi <kozokinavi@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
byteorder = "1.0"

futures = "0.1"
